# Generated by Django 6.0.4 on 2026-04-23 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_camioneta_chofer_viaje_minutos_trabajados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chofer',
            name='telefono',
        ),
        migrations.AddField(
            model_name='chofer',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chofer',
            name='camioneta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viajes.camioneta'),
        ),
        migrations.AddField(
            model_name='chofer',
            name='dni',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='camioneta',
            name='tamanio',
            field=models.CharField(choices=[('chica', 'Chica'), ('grande', 'Grande')], max_length=20),
        ),
    ]
