# Generated by Django 6.0.4 on 2026-04-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_remove_chofer_telefono_chofer_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
